# Alacritty Configuration File
# Location: $XDG_CONFIG_HOME/alacritty/alacritty.toml
# Documentation: https://alacritty.org/config-alacritty.html

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 1.0
blur = false
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 14.0

