#!/usr/bin/env bash

echo "WARNING: This is a full setup meant for new devices."
printf "Do you want to continue? [y/N]: "
read -r response

case "$response" in
    [yY][eE][sS]|[yY]) 
        echo "Continuing setup..."
        ;;
    *)
        echo "Setup aborted."
        exit 1
        ;;
esac

# Install Xcode Command Line Tools
xcode-select --install

# Install Homebrew
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install Homebrew packages
brew bundle install

# Setup dotfiles
./setup-dotfiles

# Setup zsh
./setup-zsh

# Add macOS
./setup-macos
