#!/usr/bin/env zsh
# Disable management for common floating apps we try to keep this list short
# to give the wms preference. if well configured, most apps will work well
# or can easily be unmanaged if truly needed. Keep at top to prevent shuffling
# on restart.
declare -a unmanaged_apps=(
"System Settings"
#"Finder"
"KeyCastr"
"Keka"
)
for app in "${unmanaged_apps[@]}"; do
    yabai -m rule --add app="^$app$" manage=off
done

# Initial Configuration
NUM_DISPLAYS=$(yabai -m query --displays | jq '. | length')

# depending on number of displays
if [ "$NUM_DISPLAYS" -eq 1 ]; then
    # use stack for all screens
    yabai -m config layout stack
    PAD=0
else
    # use managed bsp layout by default
    # use stack for the last space (laptop, secondary screen)
    yabai -m config layout bsp
    yabai -m config --space last layout stack
    PAD=6
fi

# When focusing a window, put the mouse at its center.
# yabai -m config mouse_follows_focus on

# Automatically focus the window under the mouse
#yabai -m config focus_follows_mouse autoraise

## Change how yabai looks
yabai -m config top_padding ${PAD}
yabai -m config bottom_padding ${PAD}
yabai -m config left_padding ${PAD}
yabai -m config right_padding ${PAD}
yabai -m config window_gap ${PAD}

# restart service on display ad/remove
yabai -m signal --add event="display_removed" action="yabai --restart-service"
yabai -m signal --add event="display_added" action="yabai --restart-service"
