#!/usr/bin/env sh
# YABAI STUFF
# as seen in: https://www.youtube.com/watch?v=JL1lz77YbUE

# use managed bsp layout by default
yabai -m config layout bsp

# use stack for the last space (laptop, secondary screen)
yabai -m config --space last layout stack

## Disable Yabai resizing
declare -a unmanaged_apps=(
    "System Settings"
    "System Information"
    "Activity Monitor"
    "Disk Utility"
    "Finder"
    "KeyCastr"
)
for app in "${unmanaged_apps[@]}"; do
    yabai -m rule --add app="^$app$" manage=off
done

# When focusing a window, put the mouse at its center.
yabai -m config mouse_follows_focus on

# Automatically focus the window under the mouse
#yabai -m config focus_follows_mouse autoraise

## Change how yabai looks
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

